title: Giulio Fabbri
description: Born in Siena (Tuscany, Italy) on January 19, 2000.I am an intern in data science, close to my master's degree.My passion has always been the analysis of economic phenomena shaping our society and I strongly believe that a scientific approach to data is the key to solving our challenges regarding the economic, environmental and social impact of our decisions.
logo: assets/Screenshot 2024-04-27 152154.png

show_downloads: true
theme: jekyll-theme-minimal
